# GeyserHub by Jens & Konicai

# Join and leave messages. Supports papi placeholders.
Join-Message:
  Enable: false
  Messages:
    - "§fWelcome §6%player_name%§f on geyser network!"
    - "§bHave a great time playing on our network!"

Join-Teleporter:
  Enable: false
  World: world
  X: 0
  Y: 65
  Z: 0
  Yaw: 0
  Pitch: 0

# The message to be sent to players whenever they are moving to a new server using a button in a form/meu
# which uses the Server functionality. Supports papi placeholders, as well as %server%, the name of the server they are moving to.
Bungeecord-Message: "§fTeleporting to §b%server%"

Scoreboard:
  Enable: false
  # Refresh rate in seconds.
  Refresh-rate: 7
  Title: "Welcome to GeyserServer"
  Lines:
    - "§f+----------------------+"
    - "§f+§b          GeyserLobby      §f+"
    - "§f+§b      Plugin provided by §f   +"
    - "§f+§b            ProjectG.        §f +"
    - "§f§f+----------------------+"
    - "§a  *  §6https://projectg.dev  §a*"


Broadcasts:
  Enable: false
  # ticks between each broadcast (default: 3 minutes)
  Interval: 3600
  Messages:
    Message1:
      - '§6 -*-*-  Welcome to GeyserNetwork  -*-*- '
    Message2:
      - '§6*----------------*----------------* '
      - '§b -*-*-*- GeyserHub -*-*-*-'
      - '§b -*-*- Made by ProjectG -*-*-'
      - '§6*----------------*----------------* '

World-settings:
  disable-hunger-loss: false
  disable-fall-damage: false
  disable-drowning: false
  disable-fire-damage: false
  disable-player-pvp: false
  disable-weather-change: false
  disable-mob-spawning: false
  disable-block-burn: false
  disable-block-fire-spread: false
  disable_block-leaf-decay: false
  disable-block-place: false
  disable-block-break: false

# Publish helpful and anonymous server metrics to https://bstats.org/plugin/bukkit/GeyserHub/13469
Bstats: true

# Toggle debug logging
Enable-Debug: false

# Don't touch this
Config-Version: 6
